version: "3"

volumes:
  mariadb_v:
    driver: local
#    name: mariadb_v
#    driver_opts:
#      device: /Users/fcoindre/data/mariadb
#      type: none
#      o: bind
  wordpress_v:
    driver: local
#    name: wordpress_v
#    driver_opts:
#      device: /Users/fcoindre/data/wordpress/
#      type: none
#      o: bind


services:
  mariadb:
    container_name: mariadb
    networks:
        - inception
    build:
        context: requirements/mariadb
        dockerfile: Dockerfile
    volumes:
        - mariadb_v:/var/lib/mysql
    restart: unless-stopped
    #ports:
        #- "3306"
    environment:
        - MARIADB_ROOT_PASSWORD=mypass
        - MARIADB_DB_NAME=db_wordpress
        - MARIADB_USER=fcoindre
        - MARIADB_PASS=mypass
    #env_file: .env

  nginx:
    container_name: nginx
    volumes:
        - wordpress_v:/var/www/wordpress
    networks:
        - inception
    depends_on:
        - wordpress
    build:
        context: requirements/nginx
        dockerfile: Dockerfile
    ports:
        - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    volumes:
        - wordpress_v:/var/www/wordpress
    networks:
        - inception
    build:
        context: requirements/wordpress
        dockerfile: Dockerfile
    depends_on:
        - mariadb
    restart: on-failure
    environment:
        - MARIADB_ROOT_PASSWORD=mypass
        - MARIADB_DB_NAME=db_wordpress
        - MARIADB_USER=fcoindre
        - MARIADB_PASS=mypass
    
    #ports:
        #- "9000"

networks:
    inception:
        driver: bridge
