version: "3"
services:
  mariadb:
    container_name: mariadb
    networks:
        - inception
    build:
        context: requirements/mariadb
        dockerfile: Dockerfile
    volumes:
        - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
        - 3306

  nginx:
    container_name: nginx
    volumes:
        - wordpress:/var/www/html
    networks:
        - inception
    depends_on:
        - wordpress
    build:
        context: requirements/nginx
        dockerfile: Dockerfile
    ports:
        - 443:443
    restart: on-failure

  wordpress:
    container_name: wordpress
    volumes:
        - wordpress:/var/www/wordpress
    networks:
        - inception
    build:
        context: requirements/wordpress
        dockerfile: Dockerfile
    depends_on:
        - mariadb
    restart: on-failure
    expose:
        - "9000"

volumes:
    mariadb:
    wordpress:

networks:
    inception:
