version: "3"

volumes:
  mariadb_v:
    driver: local
    name: mariadb_v
    driver_opts:
      device: /home/fcoindre/data/mariadb/
      type: none
      o: bind
  wordpress_v:
    driver: local
    name: wordpress_v
    driver_opts:
      device: /home/fcoindre/data/wordpress/
      type: none
      o: bind

services:
  mariadb:
    container_name: mariadb
    networks:
        - inception
    build:
        context: requirements/mariadb
        dockerfile: Dockerfile
    volumes:
        - mariadb_v:/var/lib/mysql
    restart: unless-stopped
    env_file: .env

  nginx:
    container_name: nginx
    volumes:
        - wordpress_v:/var/www/wordpress
    networks:
        - inception
    depends_on:
        - wordpress
    build:
        context: requirements/nginx
        dockerfile: Dockerfile
    ports:
        - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    volumes:
        - wordpress_v:/var/www/wordpress
    networks:
        - inception
    build:
        context: requirements/wordpress
        dockerfile: Dockerfile
    depends_on:
        - mariadb
    restart: on-failure
    env_file: .env

networks:
    inception:
        driver: bridge
